### ISSUE TITLE
File Metadata

### ISSUE THREAD

**Issue by dolanske** [Mavulp/hivefriends#10]
I'd love to understand if it's possible for the back-end to extract metadata from the image file and add them into a "metadata" field on the image object. I think metadata should live within its own object because not every image will contain all of the information. Hence it should just be a variable object.

Question though, are you able to read the uploaded file's metadata, or does the front-end have to extract it manually? I wonder how sites like google drive / images does this. 

If it turns out it's impossible for you to do, let me know and I will make sure I get it all prepped on the front end. Then we should talk about image object fields and expanding them

**Comment by Jokler** [comment]
The plan is to check for as much data as we can find and to store anything useful we can find as well as return it once the upload completes.

**Comment by Jokler** [comment]
Resolved by 3feee72ebddf7d6d245a2a555fdfeace57bb6a29.
