### ISSUE TITLE
Invalid Session Message

### ISSUE THREAD

**Issue by thechantaro** [Mavulp/hivefriends#111]
There is an Invalid Session message when viewing an album shared for third parties to view.
And it stacks with every image you browse in an album like [this](https://i.imgur.com/OIgHZLb.jpeg)

**Comment by dolanske** [comment]
This happens when you load profile images on public albums. In the author section and in the comments.

Aren't all image links public by design @Jokler? I can not ask for user images on public albums but that sounds like a workaround. I think profile images should still show imo.

**Comment by Jokler** [comment]
I don't think this is caused by the profile images since we discussed those previously and decided to hide them. Based on my testing it seems to be the image metadata for the "Photo details" sections that can't be accessed currently.

**Comment by dolanske** [comment]
Alright, I will hide the image metadata when on public image. I think it makes sense, especially if there is some sensitive information.
