### ISSUE TITLE
Move image description to better spot

### ISSUE THREAD

**Issue by APirateHat** [Mavulp/hivefriends#117]
Current spot for the image description is bad, have to scroll down to read it = that's stupid. Suggested spots: above comment field.

**Comment by fkaa** [comment]
I think the description + map + image info could all be on top of the comments sidebar maybe?

**Comment by dolanske** [comment]
Sounds good, will include this in the notification update.

**Comment by dolanske** [comment]
Does this satisfy the ask? 
![image](https://user-images.githubusercontent.com/6785973/181918315-0b5b71d4-3cb6-422e-b1dd-863bfa41c128.png)

**Comment by APirateHat** [comment]
> 

Very nice.
