### ISSUE TITLE
(refactor) Use user's username as a primary key instead of a uuid

### ISSUE THREAD

**Issue by dolanske** [Mavulp/hivefriends#13]
Reason for this is easier identification of users in the URL and other places. Simplifies user handling too 

No security implications because even with hotlinks, accessing user profile won't be allowed because the user has no access to other pages. And because the site requires a login, there is not really a point to "hide" yourself from registered users as the site is for friends and people who know each other.

**Comment by Jokler** [comment]
Resolved by 8b964c632430132b96dc92a301c2b276946a37aa.
