### ISSUE TITLE
Editing an album updates its publish date

### ISSUE THREAD

**Issue by dolanske** [Mavulp/hivefriends#130]
When updating an album, it shows up as latest album in the log and I think also on the homepage. I would like to say "user X has EDITED an album" instead of it saying uploaded.

![image](https://user-images.githubusercontent.com/6785973/183246516-1f868e29-572a-4f98-9f46-899a85bfa1f1.png)

**Comment by Jokler** [comment]
The goal is to show images that were added again, not to show the entire album as edited which doesn't really tell anyone what happened. This is a bug because the publish date shouldn't be adjusted after the initial publish anymore.
