### ISSUE TITLE
.heic images

### ISSUE THREAD

**Issue by thechantaro** [Mavulp/hivefriends#145]
dafuq bro, we ain't mac users xddd
https://i.imgur.com/7VN2zGt.png

**Comment by kilmanio** [comment]
Go take a heic

**Comment by dolanske** [comment]
I do not know how to support .heic purely on front-end. I have already tried adding it to the allowed types during upload but that did not help. I can take a second look at it but I think the backend must also be able to parse the data and I remember you actually need to purchase a license or something. @Jokler would know more

**Comment by thechantaro** [comment]
I meant more like, why is that the default selection for image types. Usually I would upload a jpg or a png and not a heic. You can obviously select all image files and then select your picture, I'm just wondering why that's the only filetype that shows up in that window, as if indicating images need to be heic.

**Comment by dolanske** [comment]
Thanks, I did not know that was the issue. I will look into it then
