### ISSUE TITLE
Adjust image rotation on the server before uploading to database

### ISSUE THREAD

**Issue by dolanske** [Mavulp/hivefriends#15]
Currently, some images get uploaded sideways. I think I heard @Jokler mention that somewhere in the image metadata, we can actually dig up what is the right rotation.

Before saving this image to database, we should correctly rotate it and save it. Doing this on the front-end is possible, but could be a heavy operation for large images. So I vouch for the back-end to handle this.

Example:

<img width="993" alt="image" src="https://user-images.githubusercontent.com/6785973/169719473-a23434a5-9a4d-4881-9d67-a96be538b15b.png">

**Comment by Jokler** [comment]
Resolved by 233029e32e0a21137c728defabe97abfbb36c88d.
