### ISSUE TITLE
(bug) Split `albumsUploaded` in user object into `albums` and `drafts`

### ISSUE THREAD

**Issue by dolanske** [Mavulp/hivefriends#20]
The front-end uses the length of `albumsUploaded` to say how many albums user uploaded. If this list contains drafts which other users cannot see, this number could become misleading.

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/6785973/170872809-198894db-c4dd-4dee-ac1c-53e5c67dd32e.png">

To fix this I suggest we either split it into two lists, or only list published albums in the user object.

**Comment by Jokler** [comment]
Fixed by 1985221ee683a09ff091dc099adb65e5e7bb9050, drafts shouldn't be visible to other users unless specifically linked to. Anything else is a bug.
