### ISSUE TITLE
Import / connect factoid database with the alias API

### ISSUE THREAD

**Issue by dolanske** [Mavulp/hivefriends#26]
1. Create functions to easily add alias key:value pairs to the database.
2. Port the existing factoid database (only image / gif ones) to the alias database

**Comment by dolanske** [comment]
@Jokler has this been completed?

**Comment by Jokler** [comment]
It depends on what you were looking for with this issue, I have a process of easily loading twitch emotes but there is nothing in the repository that aids loading aliases.
