### ISSUE TITLE
Add filters to the /api/albums endpoint

### ISSUE THREAD

**Issue by Jokler** [Mavulp/hivefriends#5]
We want to give the user options to filter on albums to make it easier to find the interesting ones, the first step would probably be to implement filtering by usernames so that the front end can display the albums of a user on their profile.
To receive filter we can use x-www-form-urlencoded data: https://docs.rs/axum/latest/axum/extract/struct.Query.html

**Comment by fkaa** [comment]
Fixed in https://github.com/Mavulp/hivefriends/commit/c7eaf6e06fb0ed636b5610671b7dc823b2f80685
