### ISSUE TITLE
Image metadata issues

### ISSUE THREAD

**Issue by dolanske** [Mavulp/hivefriends#80]
When saving image description, the `name` and `description` are ignored, while `latitude `and `longitude `get saved even if they are an empty string. The back-end should only save `lat `& `long `if they have a number value and the value is not 0.

![image](https://user-images.githubusercontent.com/6785973/174079327-e59b2855-a053-4298-8be6-989d97aa36b2.png)

The reason this causes issues is that the front-end expects the `location` object to only appear if it has values.

**Comment by Jokler** [comment]
I will have to have a look at what kind of validation can be done but 0 should be saved for sure since it is a valid location.

**Comment by Jokler** [comment]
I could not reproduce these issues with the backend, it's possible that either I already fixed it at some point or cached values caused you to see outdated values. I just implemented your expectations around the location for now.
